### ISSUE TITLE
monkey patching can't work with multi workers

### ISSUE THREAD

**Issue by lanfon72** [ashleysommer/sanic-cors#14]
```
_pickle.PicklingError: Can't pickle <function ErrorHandler.response at 0x00000258FFBC4E18>: it's not the same object as sanic.handlers.ErrorHandler.response
```

experienced exception when using `app.run()` with workers.

**Comment by ashleysommer** [comment]
Thanks for the report.
I will check it out.
It might be a problem in sanic-plugins-framework, if it is, I can fix it.

**Comment by mungojam** [comment]
@ashleysommer, did you find anything on this? It's preventing us from using multiple workers

**Comment by mungojam** [comment]
Here's the mre:

```python
from sanic import Sanic
from sanic_cors import CORS, cross_origin

app = Sanic()

CORS(app)

app.run(workers=2)
```

**Comment by ashleysommer** [comment]
@mungojam 
I sat down just now to try to reproduce and fix this error, but unfortunately I cannot reproduce it.

Using your mre above, the code executes fine. I've added `workers=2` to several of my more complex test cases and each of them work fine too.

I think I'm going to need some more information in order to get to the cause of this issue.

1. What version of sanic-cors are you using?
2. What version of sanic-plugins-framework?
3. What version of Sanic?
4. What release of Python3 are you using?
5. What OS release are you on?

@mungojam are you seeing exactly the same error that @lanfon72 has included? (`_pickle.PicklingError`)?

**Comment by mungojam** [comment]
> What version of sanic-cors are you using?
> What version of sanic-plugins-framework?
> What version of Sanic?

sanic==0.8.3
Sanic-Cors==0.9.6
Sanic-Plugins-Framework==0.6.3.dev20180717

> What release of Python3 are you using?

3.6.2 Anaconda

> What OS release are you on?

Windows 10 - 1803 though I also get the same error at work on Windows 7

Full trace:
> python runIt.py
[2018-10-31 22:45:36 -0000] [1692] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-10-31 22:45:37 -0000] [1692] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\mark\AppData\Roaming\Python\Python36\site-packages\sanic\app.py", line 732, in run
    serve_multiple(server_settings, workers)
  File "C:\Users\mark\AppData\Roaming\Python\Python36\site-packages\sanic\server.py", line 714, in serve_multiple
    process.start()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function ErrorHandler.response at 0x0000021BE968D488>: it's not the same object as sanic.handlers.ErrorHandler.response
Traceback (most recent call last):
  File "runIt.py", line 8, in <module>
    app.run(workers=2)
  File "C:\Users\mark\AppData\Roaming\Python\Python36\site-packages\sanic\app.py", line 732, in run
    serve_multiple(server_settings, workers)
  File "C:\Users\mark\AppData\Roaming\Python\Python36\site-packages\sanic\server.py", line 714, in serve_multiple
    process.start()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function ErrorHandler.response at 0x0000021BE968D488>: it's not the same object as sanic.handlers.ErrorHandler.response
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied

**Comment by ashleysommer** [comment]
Ok, I've worked out why I can't reproduce it exactly.

I'm using python 3.6 on Ubuntu Linux, and the difference comes down the the different ways Windows and POSIX systems use multiprocessing by default.

In Windows, python uses a SPAWN as seen in `multiprocessing\popen_spawn_win32.py` that has to pickle the application in order to pass it to the new process.

In Linux, python uses a FORK as seen in `multiprocessing/popen_fork.py` that does not need to pickle the application.

Anyway, I was able to reproduce the error message by simply pickling the sanic app:
```
import pickle
from sanic import Sanic
from sanic_cors import CORS, cross_origin

app = Sanic()

CORS(app)

p_app = pickle.dumps(app)

un_p_app = pickle.loads(p_app)

un_p_app.run()
```

```
Traceback (most recent call last):
  File "/home/flubba86/PycharmProjects/sanic-cors/examples/mre.py", line 9, in <module>
    p_app = pickle.dumps(app)
_pickle.PicklingError: Can't pickle <function ErrorHandler.response at 0x7f6c8d2406a8>: it's not the same object as sanic.handlers.ErrorHandler.response
```

**Comment by ashleysommer** [comment]
@mungojam 
Sanic-CORS v0.9.7 as been pushed which will _hopefully_ fix this issue for you.
(0.9.7 requires sanic-plugins-framework to be updated to 0.6.4.dev20181101)

This turned out to be the tip of the iceberg with pickle-related problems in Sanic-Plugins-Framework.
I reworked several classes and structures in SPF in order for Sanic Plugins (and Sanic apps which have SPF applied) to be able to be pickled and unpickled successfully.

Then after the SPF fixes were in place, I was able to focus on Sanic-CORS. I reworked the way the CORS exception handler is applied. This may not be quite as fast as the original version, but it is still very fast, and it allows the Sanic-CORS plugin to be able to be pickled for use in multiprocessing in Windows.

**Comment by mungojam** [comment]
Amazing, thanks. I'll give it a go today

**Comment by mungojam** [comment]
That's working perfectly for me, thanks! I will check out how you fixed the pickling if we ever get similar issues with our own code as it's all new to me

**Comment by mungojam** [comment]
I'm still getting this error on a more complex app as soon as I enable CORS. I'm going to try and do some binary searching to find out which component leads to the problem occurring.

Here's the error, don't know if that helps:

> Exception has occurred: _pickle.PicklingError
Can't pickle <function ErrorHandler.response at 0x00000000052EEAE8>: it's not the same object as sanic.handlers.ErrorHandler.response

**Comment by mungojam** [comment]
Ignore my deleted message, I had a mix-up with package versions
