### ISSUE TITLE
Sanic 19.12.2 issues with CORS

### ISSUE THREAD

**Issue by HarpoMarxHr** [ashleysommer/sanic-cors#43]
Hi, I have a question regarding CORS plugin for Sanic. 
These are packages currently installed on my system:
sanic==19.12.2
sanic-base-extension==0.1.1
Sanic-Cors==0.10.0.post3
sanic-jwt==1.4.0
Sanic-Plugins-Framework==0.9.0
sanic-redis-extension==0.1.1

I run sanic server behind uvicorn, the issue is that there is an exception on every request id CORS is implemented.

Error example:
[2020-04-16 15:02:41 +0200] [13792] [ERROR] Exception occurred while handling uri: 'http://192.168.43.55/api/auth'
Traceback (most recent call last):
  File "/home/some_user/.virtualenvs/some_venv/lib/python3.7/site-packages/sanic/app.py", line 946, in handle_request
    request, request_name=name
  File "/home/some_user/.virtualenvs/some_venv/lib/python3.7/site-packages/spf/framework.py", line 603, in _run_request_middleware_19_12
    "App must be running before you can run middleware!"
AssertionError: App must be running before you can run middleware!
ERROR:    Exception occurred while handling uri: 'http://192.168.43.55/api/auth'
Traceback (most recent call last):
  File "/home/some_user/.virtualenvs/some_venv/lib/python3.7/site-packages/sanic/app.py", line 946, in handle_request
    request, request_name=name
  File "/home/some_user/.virtualenvs/some_venv/lib/python3.7/site-packages/spf/framework.py", line 603, in _run_request_middleware_19_12
    "App must be running before you can run middleware!"
AssertionError: App must be running before you can run middleware!
[2020-04-16 15:02:41 +0200] [13792] [INFO] POST - http://192.168.43.55/api/auth - 500

**Comment by ashleysommer** [comment]
Sorry for late reply.
This was discussed in #47
And was fixed in Sanic-Plugins-Framework v0.9.3
