### ISSUE TITLE
Usage of ASGI client with CORS

### ISSUE THREAD

**Issue by ahopkins** [ashleysommer/sanic-cors#47]
I think this is a problem more with SPF than this project. However, there is an exception when trying to run the ASGI test client.

```
_, response = await app.asgi_client.post("/foo/bar", json=data)
```

```
Traceback (most recent call last):
  File "/home/adam/.virtualenvs/pf/lib/python3.7/site-packages/sanic/app.py", line 910, in handle_request
    response = await self._run_request_middleware(request)
  File "/home/adam/.virtualenvs/pf/lib/python3.7/site-packages/spf/framework.py", line 533, in _run_request_middleware
    "App must be running before you can run middleware!"
AssertionError: App must be running before you can run middleware!
```

There is a [PR on the Sanic repo](https://github.com/huge-success/sanic/pull/1894) that would help this by adding a `test_mode` flag to the app instance.

**Comment by ashleysommer** [comment]
@ahopkins 
I'm not completely up to speed on all of the asgi features in Sanic. Is `asgi_client` only used when testing, ie is it a type of test_client? Or would there be other cases whan a user would use asgi_client to call into their app?

**Comment by ahopkins** [comment]
It is a test client only. It reaches in and executes the Middleware, listeners, and handlers without having to startup a server.

**Comment by ashleysommer** [comment]
Ok, I might have to think about this some more.

SPF does some initialization on the app's `after_server_start` hook (or `before_server_start` depending on Sanic version and mode of operation). This initialization step transitions SPF from its "setup" state to its "operational" state, ready to have requests passed through it.

Executing a route (or middleware) on the Sanic app without first booting the app causes the request to be pass through SPF while it is still in its "setup" state, and results in unspecified operation, that is why there is an assertion inserted at that point.

The message "App must be running before you can run middleware!" could definitely be tweaked to make it more clear why the error is emitted.

Its not reasonable to expect the `asgi_client` to boot the app for every request either, that would defeat the purpose.

The `test_mode` check might help here. SPF might be able to put itself in a kind of 'serverless' state. But until that is merged, I might be able to come up with another way of getting this to work.

**Comment by ahopkins** [comment]
Yeah, I'd say let's get test mode merged and released and the sanic test client broken out. They seem like that would help a lot.
As for CORS, it seems like that is a Middleware that could probably be skipped in test mode. Maybe that's an option?

**Comment by ashleysommer** [comment]
Yep, simplest way forward would be simply skip all SPF-derived routes and middleware when in test mode. That wouldn't matter for something like CORS, but for more 

This PR https://github.com/huge-success/sanic/pull/1894 is still showing test errors. Is it ok to merge as-is?

**Comment by ahopkins** [comment]
> This PR [huge-success/sanic#1894](https://github.com/huge-success/sanic/pull/1894) is still showing test errors. Is it ok to merge as-is?

Yes, after I figure those tests out.

**Comment by ashleysommer** [comment]
@ahopkins I've pushed a new version of Sanic-Plugins-Framework v0.9.3, it has a simple mechanism to switch SPF into serverless "running" mode if a request is received before the app is started, and the app is in asgi mode.

Can you please upgrade your SPF to 0.9.3 to see if it fixes this problem for you?
